
robóticaII: 
	pandoc --pdf-engine=xelatex   \
		-V papersize:a4paper    \
		--template=./LaTeX_ES.latex    \
		--reference-doc=plantilla_roboticaII.docx \
		-o  "Robótica II con microbit.docx"  \
		Cabecera.md        \
		Cabecera_latex.md \
		1.Ejemplos_microbit.md \
		2.Uso_pines.md \
		3.Kit_avanzado.md \
		4.Proyectos.md \
